# Site settings
title: Instructional Design Portfolio
email: LoganAllums@gmail.com
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://loganaq.github.io/" # the base hostname & protocol for your site

twitter_username: Logan Quinn
github_username: LoganAQ

# Build settings
markdown: kramdown
